[package]
name = "aoc2024"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.11"
itertools = "0.13.0"
rayon = "1.10.0"

[lib]
name = "aoc2024"
path = "src/lib.rs"

[[bin]]
name = "day01"
path = "src/bin/day01.rs"
